### ISSUE TITLE
runner missing from zip

### ISSUE THREAD

**Issue by rogerjak** [carlpett/xUnit-TeamCity#22]
Hi, downloaded the 1.2.0-alpha and the xunit 2.2 test runner is missing from the zip

**Comment by carlpett** [comment]
@rogerjak Thanks for reporting! I will look at this during the weekend. Sorry about the broken build!

**Comment by carlpett** [comment]
I've been debugging the CI build for a while, but I can't figure out why it won't add the 2.2 runner. It does it when building locally. 

I've uploaded a locally built version instead, which should work. Please let me know if it works for you!
