### ISSUE TITLE
Support for xUnit 2.2.0?

### ISSUE THREAD

**Issue by sdepouw** [carlpett/xUnit-TeamCity#24]
Just installed the latest version of the plugin, and within TeamCity it is only allowing me to select 2.1.0, 2.0.0, and 1.9.2. My xUnit install in my project is 2.2.0, however (as a .NET Core App, a project created via the "dotnet" CLI). When TeamCity runs against the DLL, I am getting "System.InvalidOperationException: Unknown test framework: could not find xunit.dll (v1) or xunit.execution.*.dll (v2) in path\to\agent\work\abc123\UnitTestProject\bin\debug\netcoreapp1.1", which led me to check the version the Build Step is configured for.

**Comment by carlpett** [comment]
Hi!
What version of the plugin are you using? There is pre-release support for xUnit 2.2 in plugin version 1.2, which you can test out if you'd like. I haven't had time to do testing on .net core, however, so it is possible there are some issues there.

I hope to be able to do a proper 1.2 release soon, but there is an issue related to how I originally implemented against the TeamCity API which requires me to rewrite a fair chunk of code. I may have to push that to a later version, though.

**Comment by sdepouw** [comment]
We used whatever latest one was offered in GitHub (under Releases). But it
turns out that for .net Core the built-in CLI for core, "dotnet test",
works without issue and without need of the additional runner, so we ended
up abandoning usage of the console runner.

Thanks!

**Comment by carlpett** [comment]
Ok, great!
