### ISSUE TITLE
Missing 2.2.0 in Runner Parameters

### ISSUE THREAD

**Issue by wsain001** [carlpett/xUnit-TeamCity#25]
2.2.0 does not appear in Runner type: xUnit -> Runner Paramterers -> XUnit version. 
Only 1.9.2, 2.0.0, and 2.1.0 show up.
![xunit_bug](https://cloud.githubusercontent.com/assets/16338308/26002351/5e3f3e66-36fd-11e7-9faf-059ad05765dc.png)

**Comment by carlpett** [comment]
Hi,
Thanks for reporting! The readme file and latest (non-prerelease) release are out of sync. I will make a new release shortly which will contain 2.2.0 support!

**Comment by carlpett** [comment]
Please check out the newly released version 1.2 :)
