### ISSUE TITLE
No assemblies were matched - no tests will be run!

### ISSUE THREAD

**Issue by lvthillo** [carlpett/xUnit-TeamCity#27]
We are using TeamCity 2017.1.3 (build 46961).  
We use xUnit plugin 1.1.2

```
xUnit    Runs tests written in xUnit | 1.1.2 | Capeit | <TeamCity Data Directory>\plugins\.unpacked\xUnit
```

Our build configuration:
- MSBuild to build app
- MSBuild to build tests: This creates some \bin\Debug in our work folder and it contains our xxx.Tests.dll
- Use xUnit to execute the tests. Runner Type xUnit, XUnit version: 2.1.0. Path to our .dll. I even tried to define the path hardcoded. I put some CMD job before to check if it was able to find the file and path and everything was fine. But the output of our xunit job is:

```
[09:54:46][Step 5/6] Runner parameters { Version = 2.1.0, runtime = .NET 4.5, platform = AnyCPU/MSIL}
[09:54:46][Step 5/6] Starting test runner at E:\TeamCity\buildAgent\tools\xunit-runner\bin\2.1.0\xunit.console.exe
[09:54:46][Step 5/6] No assemblies were matched - no tests will be run!
```

**Comment by carlpett** [comment]
Hi,
Sorry to hear that! Could you share your folder structure and the value of the "Assemblies containing tests" parameter?

**Comment by lvthillo** [comment]
@carlpett Thank you for the quick reply.
This is the input of our 'Assemblies containing tests:' parameter
`%system.teamcity.build.checkoutDir%\src\app.Test\bin\Debug\name.Web.Test.dll`

The environment variable exists. We're using it in other buildsteps too and we're able to '`cd`' to that specific folder.

I don't really know what you mean with the folder structure. But I can tell you the following:
`Path/to/workspace/`:
```
src/
tools/
lib/
...
```

Inside src/ we have a `test/` folder. After the execution of the job which builds our unittests, there is a `bin/Debug` folder in it which contains our `test.dll`.

**Comment by carlpett** [comment]
Hm, it looks like I might not be expanding variables in that parameter, which would explain it. However, the search is done relative to the current working directory, which is probably identical to `%system.teamcity.build.checkoutDir%`, could just try to just remove that and specify `src\app.Test\bin\Debug\name.Web.Test.dll` instead?

**Comment by lvthillo** [comment]
@carlpett Okay, that was the issue. My apologizes! Thank you very much.

**Comment by carlpett** [comment]
No, it _should_ work, but apparently it does not. Great that the workaround works for you, though!
I'll fix the parameter expansion as soon as possible.

**Comment by osya** [comment]
I have the same issue:
```
Step 5/6: Run xUnit tests via `xUnit` runner (xUnit)
[14:55:37][Step 5/6] Runner parameters { Version = 2.4.x, runtime = .NET 4.5, platform = AnyCPU/MSIL}
[14:55:37][Step 5/6] Number of parallel processes is set to: 1
[14:55:37][Step 5/6] Starting test runner at C:\TeamCity\buildAgent\tools\xunit-runner\bin\2.4.x\xunit.console.exe
[14:55:37][Step 5/6] No assemblies were matched - no tests will be run!
```
