### ISSUE TITLE
Update .Net Framework requirements to support framework 4.7

### ISSUE THREAD

**Issue by jesuissur** [carlpett/xUnit-TeamCity#31]
Hi there

We've installed the latest EAP (2017.2) and the plugin stopped working because it depends on a framework that is installed on the agent but does not exists as agent configuration.

It would be nice to update the requirement as the first one in the image

![image](https://user-images.githubusercontent.com/136296/32445019-7a38083a-c2d2-11e7-9a98-55b1960d3596.png)

**Comment by carlpett** [comment]
Hi,
Thanks for the report, and sorry for the slow response. I'll fix this, good catch!

**Comment by carlpett** [comment]
When looking a bit closer, it wasn't exactly as simple as I had thought (the requirement is set dynamically depending on the selected runtime for xUnit). What frameworks does your agent report that is has? I

**Comment by jesuissur** [comment]
Hi 

I've made the following change locally and it works on my case.  Not sure it is the best practice on the code base so I did not made a pull request

xunit-server\src\main\java\se\capeit\dev\xunittestrunner\XUnitTestRunType.java
before:
`
        else if (runtime.equals(Runtime.dotNET45)) {
            frameworkMatcher = "4.[56](\\.[0-9]+)?"; // Match 4.5+
        }
`
after:
`
        else if (runtime.equals(Runtime.dotNET45)) {
            frameworkMatcher = "4.[5-9](\\.[0-9]+)?"; // Match 4.5+
        }
`

Those are my agent parameters about .Net
![image](https://user-images.githubusercontent.com/136296/32728104-16ab5bac-c84d-11e7-937e-5b61fae66138.png)

Thanks
Phil

**Comment by carlpett** [comment]
Hi,
That looks like the exact right change, so a PR for that would be great!
Apparently my agents are a bit outdated, I'll need to have a look at that. Thanks for the image!

**Comment by jesuissur** [comment]
Pull Request https://github.com/carlpett/xUnit-TeamCity/pull/32

**Comment by carlpett** [comment]
Thanks a lot! I've merged it, will make a new release in a bit.
