### ISSUE TITLE
Release 1.2.1 is not available in the TeamCity plugins area

### ISSUE THREAD

**Issue by RichardSinden** [carlpett/xUnit-TeamCity#34]
Hi, 

Thanks for updating the plugin to support .NET 4.7, but the version available at https://plugins.jetbrains.com/plugin/8909-xunit-test-runner is still 1.2.0 and it took me a while to realise there was 1.2.1 release available on here. I'm all good now, but it'd be worth updating it to save other people time.

Thanks,
Richard

**Comment by carlpett** [comment]
Whoops! Thanks for noticing! I have updated it now.
