### ISSUE TITLE
Agent requirements not met - no compatible agents

### ISSUE THREAD

**Issue by acadieman** [carlpett/xUnit-TeamCity#35]
Hi,

We have a client having an issue when enabling their "xUnit Units Test" build step.
When they turn on the step, they have 0 compatible agents because of the following requirement which is not met:  Exists=>DotNetFramework4.[56](\.[0-9]+)?_(x86|x64)

When looking at any of our agents under "configuration parameters", the parameters jump from 3.5 to 4.7 even though 4.5 and 4.6 are installed on all our Build Machines. 

![dotnetframework](https://user-images.githubusercontent.com/35851486/35459791-9ad7a178-02af-11e8-9b5b-d7df198fb19e.png)

![dotnetframework2](https://user-images.githubusercontent.com/35851486/35459874-ed9e4c5e-02af-11e8-870e-84dcc3c32087.png)

We are using version 1..1.3 of the plugin and running on TeamCity version 2017.2.1 (build 50732)

Thanks, let me know if you require more info

**Comment by carlpett** [comment]
Hi @acadieman,
This should be fixed in 1.2.1, thanks to #32. Could you give that a try?

**Comment by carlpett** [comment]
Assuming this is fixed. Let me know if it doesn't work!
