### ISSUE TITLE
Support for xUnit 2.4.0

### ISSUE THREAD

**Issue by DerDreschner** [carlpett/xUnit-TeamCity#38]
Hey,

we have some issues with the xUnit versions < 2.4.0. Some important bugfixes are included there.

So, is it possible to get support for xUnit 2.4.0?

Thank you!

Best reguards,
David

**Comment by carlpett** [comment]
Sorry for the lack of activity here. It should be quite straightforward, I'll try to get it done during the weekend.

**Comment by DerDreschner** [comment]
That would be really great! Thank you very much in advance!

**Comment by carlpett** [comment]
Opened a PR (#43), but lacking the time right now to do proper testing. Would you be able to do a test run? The PR build is here: https://18-37407807-gh.circle-artifacts.com/0/root/project/target/xUnit.zip

**Comment by DerDreschner** [comment]
Thank you very much for your efforts! We've tested the PR build with teamcity 2018.1.3 and everything looks good with xUnit 2.4.1! 👍 Thank you very much!!
