### ISSUE TITLE
Platform parameter gets reset to default value when editing the step

### ISSUE THREAD

**Issue by pawlos** [carlpett/xUnit-TeamCity#39]
The plugin works fine with one exception that I've observed. 

Whenever I set the platform parameter to be `x86` and then edit the step the value is being reset to `AnyCPU/MSIL`. But when I check the HTML for this dropdown the `selected` attribute is set correctly on `x86`.

Haven't observed anything like that on any other plugins but not sure if this is only xUnit-TeamCity plugin related.

TC version: 2018.1.2 (build 58537)
Plugin version: 1.2.1-3-g59671cf

It looks like the same behavior is with `Version` parameter.
Let me know if more info is needed.

**Comment by tomaszprasolek** [comment]
I also have that problem.

TeamCity: 2018.1.2 (build 58537)
xUnit Plugin: 1.2.1-3-g59671cf

**Comment by tomaszprasolek** [comment]
In TeamCity 2018.1.3 still is that bug.

**Comment by pawlos** [comment]
I think the problem is in the plugin. I've tried looking at this issue for some time but didn't see anything obvious there.

**Comment by carlpett** [comment]
Hey,
Sorry for the lack of activity here. I don't have an environment to test in at the moment, but I'll see if I can set one up.
Do any of you know if this stopped working in new versions of TC? I do think it _used_ to work, but it is quite possible there have been breaking changes in TC since then.

**Comment by carlpett** [comment]
Found the problem now, looks like some of the javascript in the plugin doesn't work any more.

**Comment by pawlos** [comment]
@carlpett thanks for the fix. Will there be any release soon or can I somehow download the package with the fix from CircleCI?

**Comment by carlpett** [comment]
I was hoping to get a fix for #38 in too in the next release, but if I don't find time before the end of the week to fix that I'll just release this.
Sounds good?

**Comment by pawlos** [comment]
Yup. Perfect!

**Comment by tomaszprasolek** [comment]
I've updated the plugin. It works. Thanks.
