### ISSUE TITLE
BadImageFormatException when building as x86.

### ISSUE THREAD

**Issue by SingleCopy** [carlpett/xUnit-TeamCity#4]
If you specify the target build to x86, the test runner calls the 64bit xunit console which throws a System.BadImageFormatException. 

Would it be possible to specify the target platform and if x86 is picked to call xunit.console.x86.exe when setting up the build step?

**Comment by carlpett** [comment]
Hi @SingleCopy: Good idea! I'll add it to the feature requests, should be fairly simple to do.

**Comment by evil-shrike** [comment]
+1 
please add an ability to run under x86-process. I'm also experiencing BadImageFormatException  as my test assembly was build under x86 (there's a reason for this).

**Comment by kj0001** [comment]
Also +1. I'm having the same issue.

**Comment by carlpett** [comment]
I've finally had time to do some work on the plugin, and just uploaded a 1.1-prerelease version which supports setting the platform. @SingleCopy @evil-shrike or @kj0001, if any of you have a possibility to test that would be greatly appreciated! 
I will do some more testing on my own production environments the upcoming week before declaring it final - primarily to verify backwards compatibility, as new parameters are introduced.

**Comment by carlpett** [comment]
We had a strange regression when I tested this internally, which turned out to be a bug in one of the teams' workflow. So, 1.1 is now released, and fixes this :)
