### ISSUE TITLE
can't select higher than 4.5 version of .NET Runtime

### ISSUE THREAD

**Issue by ivan-kadyka** [carlpett/xUnit-TeamCity#40]
Hello. We use xUnit TeamCity plugin (version = 2.2.0) and our build agents use 4.7.1 .net runtime. We can't use this plugin with this environment, only 4.5 .net runtime

![xunitbuildstep](https://user-images.githubusercontent.com/11837344/47847426-3cf47f00-dddc-11e8-9d28-5f8529061bfb.png)

**Comment by carlpett** [comment]
Hi @ivan-kadyko,
Sorry for the lack of activity here. Did you close the issue because your problem is solved?

**Comment by osya** [comment]
I have the same issue. How you solved it?
