### ISSUE TITLE
Version 1.3.0, but in teamcity-plugin.xml, version is 1.1.0

### ISSUE THREAD

**Issue by iamwilliamkwok** [carlpett/xUnit-TeamCity#44]
The version number in the teamcity-plugin.xml in the xUnit.zip 1.3.0 file appears to be incorrect.  The xml file contains <version>1.1.0</version>, but the version of xUnit TeamCity plugin is 1.3.0.

**Comment by carlpett** [comment]
Hi @hikwoky,
Thanks, there was a missing step when I upgraded the CI. I just published 1.3.1, which should be correct.
