### ISSUE TITLE
Cannot create build step in TeamCity 9.1.6

### ISSUE THREAD

**Issue by gitfool** [carlpett/xUnit-TeamCity#7]
I'm trying out this plugin ([1.1-prerelease](https://github.com/carlpett/xUnit-TeamCity/releases/tag/1.1-prerelease)) for the first time on TeamCity 9.1.6 with xUnit 2.1.0.

When I add the build step the _Save_ and _Cancel_ buttons are missing, so I can't create it:

![image](https://cloud.githubusercontent.com/assets/750121/12875504/fe0f0cbc-ce50-11e5-8b1b-5f3960714888.png)

^^ missing buttons ^^

Clicking on _Show advanced options_ does not do anything either.

**Comment by gitfool** [comment]
So I tried reinstalling the plugin, to no avail:
- Stop TeamCity Server
- Delete plugin from plugins directory
- Start TeamCity Server
- Confirm plugin removed
- Stop TeamCity Server
- Copy xUnit.zip to plugins directory
- Start TeamCity Server
- Confirm plugin installed

**But** then I managed to get the _Save_ and _Cancel_ buttons to appear by doing the following:
- Add build step
- Select runner type _Xcode Project_ (first runner above)
- The buttons appear
- Select runner type _XUnit_
- The buttons are still there!

Very strange. Assuming your plugin is not misconfigured for TeamCity 9.1.6, it looks like this could be a bug in TeamCity itself.

**Comment by carlpett** [comment]
Hi @gitfool,
Thanks for reporting! Could you check your browser javascript console for error messages? I've seen this happen when something goes wrong in the javascript filtering.

**Comment by carlpett** [comment]
Ok, I managed to reproduce it. Apparently there is a race condition in where I filter unsupported platform/versions, so that it can try to do so before the dropdown library in use in TeamCity is done initializing. 
While I fix it, unless you need to use the x86 platform support introduced in 1.1, you could try the 1.0 release instead?

**Comment by carlpett** [comment]
I made a new prerelease with a fix for this. Hopefully I'll have time to finish regression testing in a larger environment next week so I can release a full version.
