### ISSUE TITLE
Transpose to jenkins

### ISSUE THREAD

**Issue by yannickameur** [carlpett/xUnit-TeamCity#8]
Hello
Do you do it for too Jenkins?
Thanks for your response

**Comment by carlpett** [comment]
Hi!
I'm not sure if I understand, do you mean if the plugin is compatible with Jenkins? If so, I'm afraid not. They use completely different systems.

**Comment by yannickameur** [comment]
No, i says fork for create the same plugin into Jenkins.

**Comment by carlpett** [comment]
I see. Feel free to use it as inspiration :)
